languageCode = "en-us"
title = "TutorialEdge.net"
baseURL = "https://tutorialedge.net"
paginate = 9
pygmentsCodeFences = true
[indexes] 
    category = "categories" 
    tag = "tags" 
    series = "series"
    course = "course"
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
[params.algolia]
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "description"]
    params = ["categories", "tags"]
[outputs]
    home = ["HTML", "RSS", "Algolia"]