languageCode = "en-us"
title = "TutorialEdge.net"
baseURL = "https://tutorialedge.net"
paginate = 9
pygmentsCodeFences = true
[indexes] 
    category = "categories" 
    tag = "tags" 
    series = "series"
    course = "course"
